name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          ssh -p 2222 OFFSIDE@102.88.108.26 "cd fastapi-book-project/main.py && git pull origin main && sudo systemctl restart main.service"
