name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Match the version your app uses

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy to Vercel using the Vercel CLI
      - name: Deploy to Vercel
        env: # Provide Vercel tokens as environment variables
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          python -m pip install vercel
          vercel --token $VERCEL_TOKEN --prod --confirm
