name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          ssh OFFSDIE@2c0f:f5c0:601:b4a1:155c:b702:c0ef:29c0 "cd fastapi-book-project/main.py && git pull origin main && sudo systemctl restart app.service"
